Add qt.conf file to build instructions
PolySync/PolySync-CPP-Examples pull request #70
Opened 2017-05-10 19:54 UTC by adolfoapolloni

Before this commit, the build instructions did not tell the user to copy a qt.conf file
into the build directory. This prevented the QtImageViewer from functioning properly.
This commit fixes that by updating the Readme to contain the appropriate instructions.

2017-05-11 17:10 UTC, ltbj requested changes

2017-05-11 17:10 UTC, ltbj commented on QtImageViewer/README.md
> +7. After building the QtImageViewer, move a qt.conf file into the build file for the QtImageViewer.
We need to include what the contents of the `qt.conf` file are, and track an example of this file in a new `./res` directory. 

Here's the contents of the file:

```
[Paths]
Plugins=/usr/local/polysync/bin
```

2017-05-16 15:47 UTC, adolfoapolloni commented on QtImageViewer/README.md
> +7. After building the QtImageViewer, move a qt.conf file into the build file for the QtImageViewer.
A description of the contents of the qt.file is added. How do I track an example of the file in a ./res directory? The problem I am having is how do get an example of the qt.conf file as qt image viewer is a paid application?

2017-05-16 17:56 UTC, adolfoapolloni commented on QtImageViewer/README.md
> +7. After building the QtImageViewer, move a qt.conf file into the build file for the QtImageViewer.
Everything should be fixed

2017-05-16 18:18 UTC, ltbj commented
You need to point your pull request at  the `devel` branch, not `master`.

2017-05-16 18:18 UTC, closed without merging

2017-05-16 18:24 UTC, ltbj commented
My bad, there is no `devel` branch on this repo.